name : "c9_practice"


services:
  auth-api-service : 
    image: 'auth-api-img'
    build : 
      context: ./auth_service
      dockerfile : Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./auth_service:/code"
    networks:
      - auth-network

networks:
  auth-network:
